- hosts: localhost
  tasks:
  - name: "Installing Python Package"
    package:
            name: "python3"
  - name: "Installing boto3 library"
    pip:
            name: "boto3"
  - name: "Launching webserver instance"
    ec2_instance:
            region: "ap-south-1"
            name: "webserver"
            instance_type: "t2.micro"
            wait: yes
            wait_timeout: 20
            key_name: "mymainkey1122"
            image_id: "ami-08e0ca9924195beba"
            security_group: "sg-04f4c03f3c35168c3"
            state: present
    register: webserver
  - name: Updating inventory with instance ip
    blockinfile:
       path: inventory.txt
       marker: "# 1st {mark} ANSIBLE MANAGED BLOCK "
       block: |
               [{{ webserver.instances[0].tags.Name }}]
               {{ webserver.instances[0].public_ip_address }}
